version: "3.9"
networks:
  main:
    name: main
services:
  ipfs-cluster-0:
    profiles: ["ipfs"]
    container_name: ipfs-cluster-0
    networks:
      - main
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs-node-0
    environment:
      CLUSTER_PEERNAME: ipfs-cluster-0
      CLUSTER_SECRET: 724931756d306e6d56685055714966347373424e77484d733369575433364d42
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-node-0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9099 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9099:9099"
    volumes:
      - ./ipfs-cluster-0/config:/data/ipfs-cluster
  ipfs-node-0:
    profiles: ["ipfs"]
    container_name: ipfs-node-0
    networks:
      - main
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    environment:
      LIBP2P_FORCE_PNET: '1'
    volumes:
      - ./staging_dir:/export
      - ./pv-data_dir:/data/pv
      - ./ipfs-node-0:/data/ipfs
      - ./private-ipfs-network/.ipfs/swarm.key:/data/ipfs/swarm.key
      - ./private-ipfs-network/init.sh:/usr/local/bin/start_ipfs
  ipfs-cluster-1:
    profiles: ["ipfs"]
    container_name: ipfs-cluster-1
    networks:
      - main
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs-node-1
    environment:
      CLUSTER_PEERNAME: ipfs-cluster-1
      CLUSTER_SECRET: 724931756d306e6d56685055714966347373424e77484d733369575433364d42
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-node-1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./ipfs-cluster-1/config:/data/ipfs-cluster
  ipfs-node-1:
    profiles: ["ipfs"]
    container_name: ipfs-node-1
    networks:
      - main
    image: ipfs/go-ipfs:latest
    environment:
      LIBP2P_FORCE_PNET: '1'
    volumes:
      - ./pv-data_dir:/data/pv
      - ./ipfs-node-1:/data/ipfs
      - ./private-ipfs-network/.ipfs/swarm.key:/data/ipfs/swarm.key
      - ./private-ipfs-network/init.sh:/usr/local/bin/start_ipfs
  ipfs-cluster-2:
    profiles: ["ipfs"]
    container_name: ipfs-cluster-2
    networks:
      - main
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs-node-2
    environment:
      CLUSTER_PEERNAME: ipfs-cluster-2
      CLUSTER_SECRET: 724931756d306e6d56685055714966347373424e77484d733369575433364d42
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs-node-2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./ipfs-cluster-2/config:/data/ipfs-cluster
  ipfs-node-2:
    profiles: ["ipfs"]
    container_name: ipfs-node-2
    networks:
      - main
    image: ipfs/go-ipfs:latest
    environment:
      LIBP2P_FORCE_PNET: '1'
    volumes:
      - ./pv-data_dir:/data/pv
      - ./ipfs-node-2:/data/ipfs
      - ./private-ipfs-network/.ipfs/swarm.key:/data/ipfs/swarm.key
      - ./private-ipfs-network/init.sh:/usr/local/bin/start_ipfs
